"""add_tweet_metrics_and_author_info

Revision ID: 3273580f2b6c
Revises: 12719228d0d9
Create Date: 2025-01-29 19:02:24.274408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3273580f2b6c'
down_revision: Union[str, None] = '12719228d0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('author_username', sa.String(), nullable=True))
    op.add_column('tweets', sa.Column('author_name', sa.String(), nullable=True))
    op.alter_column('tweets', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_tweets_tweet_id', 'tweets', type_='unique')
    op.drop_index('ix_tweets_tweet_id', table_name='tweets')
    op.create_index(op.f('ix_tweets_tweet_id'), 'tweets', ['tweet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_tweet_id'), table_name='tweets')
    op.create_index('ix_tweets_tweet_id', 'tweets', ['tweet_id'], unique=False)
    op.create_unique_constraint('uq_tweets_tweet_id', 'tweets', ['tweet_id'])
    op.alter_column('tweets', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tweets', 'author_name')
    op.drop_column('tweets', 'author_username')
    # ### end Alembic commands ###
