"""rename_date_fields

Revision ID: 7a069ddcb867
Revises: 096c67c7583b
Create Date: 2025-03-20 17:50:59.403396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a069ddcb867'
down_revision: Union[str, None] = '096c67c7583b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('end', sa.DateTime(), nullable=False))
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'end')
    op.drop_column('events', 'start')
    # ### end Alembic commands ###
