"""add_tweet_metrics_and_author_info

Revision ID: 97c7c7fee63e
Revises: 3273580f2b6c
Create Date: 2025-01-29 20:02:11.296658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c7c7fee63e'
down_revision: Union[str, None] = '3273580f2b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
